#!/usr/bin/python3

import subprocess, time
import argparse, sqlite3
from configparser import ConfigParser
from datetime import datetime
from colorama import Fore, Back, Style

configfile = '/home/ark/pyark.cfg'

YEL = Fore.YELLOW+Style.NORMAL
BYEL = Fore.YELLOW+Style.BRIGHT
CYN = Fore.CYAN+Style.NORMAL
BCYN = Fore.CYAN+Style.BRIGHT
WHT = Fore.WHITE+Style.NORMAL
BWHT = Fore.WHITE+Style.BRIGHT
MGT = Fore.MAGENTA+Style.NORMAL
BMGT = Fore.MAGENTA+Style.BRIGHT
GRN = Fore.GREEN+Style.NORMAL
BGRN = Fore.GREEN+Style.BRIGHT
RED = Fore.RED+Style.NORMAL
BRED = Fore.RED+Style.BRIGHT
RST = Fore.RESET+Style.NORMAL

class ExtConfigParser(ConfigParser):
    def getlist(self, section, option):
        value = self.get(section, option)
        return list(filter(None, (x.strip() for x in value.split(','))))

    def getlistint(self, section, option):
        return [int(x) for x in self.getlist(section, option)]

config = ExtConfigParser()
config.read(configfile)

sharedpath = config.get('general', 'shared')

sqldb = f'{sharedpath}/db/pyark.db'

def playedTime(ptime):
    total_min = ptime / 60
    minutes = int(ptime % 60)
    if minutes == 1:
        minstring = 'Min'
    else:
        minstring = 'Mins'
    hours = int(total_min / 60)
    if hours == 1:
        hourstring = 'Hour'
    else:
        hourstring = 'Hours'
    days = int(hours / 24)
    if days == 1:
        daystring = 'Day'
    else:
        daystring = 'Days'
    if days != 0:
        return('{} {}, {} {}'.format(days, daystring, hours-days*24, hourstring))
    elif hours != 0:
        return('{} {}, {} {}'.format(hours, hourstring, minutes, minstring))
    elif minutes != 0:
        return('{} {}'.format(minutes, minstring))
    else:
        return('Error')

def elapsedTime(start_time, stop_time, lshort=False):
    diff_time = start_time - stop_time
    total_min = diff_time / 60
    minutes = int(total_min % 60)
    if minutes == 1:
        if lshort is False:
            minstring = 'minute'
        else:
            minstring = 'min'
    else:
        if lshort is False:
            minstring = 'minutes'
        else:
            minstring = 'mins'
    hours = int(total_min / 60)
    if hours == 1:
        if lshort is False:
            hourstring = 'hour'
        else:
            hourstring = 'hr'
    else:
        if lshort is False:
            hourstring = 'hours'
        else:
            hourstring = 'hrs'
    days = int(hours / 24)
    if days == 1:
        if lshort is False:
            daystring = 'day'
        else:
            daystring = 'day'
    else:
        if lshort is False:
            daystring = 'days'
        else:
            daystring = 'days'
    if days != 0:
        return('{} {}, {} {} ago'.format(days, daystring, hours, hourstring))
    elif hours != 0:
        return('{} {}, {} {} ago'.format(hours, hourstring, minutes, minstring))
    elif minutes > 1:
        return('{} {} ago'.format(minutes, minstring))
    elif minutes <= 1:
        return('now')
    else:
        log.error('Elapsed time function failed. Could not convert.')
        return('Error')

print('    ')

conn = sqlite3.connect(sqldb)
c = conn.cursor()

now = time.time()

c.execute('DELETE from players WHERE playedtime = 0')
conn.commit()

c.execute('SELECT * from players')
allplayers = c.fetchall()

def howmanyon(inst):
    pcnt = 0
    for row in allplayers:
        #print(row)
        diff_time = float(now) -  float(row[2])
        total_min = diff_time / 60
        minutes = int(total_min % 60)
        hours = int(total_min / 60)
        days = int(hours / 24)
        if minutes <= 1 and hours < 1 and days < 1 and row[3] == inst:
            pcnt += 1
    return pcnt

for row in allplayers:
    #print(row)
    if row[0] == '' or row[0].startswith(' '):
        print(f'deleting id: {row[0]}')
        c.execute('DELETE from players WHERE steamid = ?', (row[0],))
    else:
        pltime = playedTime(float(row[4].replace(',','')))
        laston = elapsedTime(float(now),float(row[2]))
        diff_time = float(now) -  float(row[2])
        total_min = diff_time / 60
        minutes = int(total_min % 60)
        hours = int(total_min / 60)
        days = int(hours / 24)
        if minutes <= 1 and hours < 1 and days < 1:
            active = BGRN
        elif days > 7 <= 14:
            active = YEL
        elif days > 14:
            active = BRED
        else:
            active = BCYN
        firston = datetime.fromtimestamp(float(row[6])-14400).strftime('%a, %b %d %I:%M%p')
        print(f'{active}{row[0]} \"{row[1]}\" - Connections: {row[7]} - Reward Points: {row[5]}')
        print(f' FirstON: {firston} | PlayedTime: {pltime} | LastON: {laston} on {row[3]}{RST}')
        print('  ')


c.execute('SELECT cfgver from general')
gencfgver = c.fetchone()

print(f'Current Config Version: {BGRN}{gencfgver[0]}{RST}')

print('    ')

c.execute('SELECT * from instances')
allservers = c.fetchall()

for each in allservers:

    restarted = elapsedTime(float(now),float(each[1]))
    if float(now)-float(each[1]) > 1209600:
        restclr = f"{BRED}"
    elif float(now)-float(each[1]) > 604800:
        restclr = f"{BYEL}"
    else:
        restclr = f"{BGRN}"
    lwipe = elapsedTime(float(now),float(each[2]))
    if float(now)-float(each[2]) > 86400:
        wipeclr = f"{BRED}"
    elif float(now)-float(each[2]) > 43200:
        wipeclr = f"{BYEL}"
    else:
        wipeclr = f"{BGRN}"
    lvote = elapsedTime(float(now),float(each[4]))
    if float(now)-float(each[4]) > 604800:
        voteclr = f"{BRED}"
    elif float(now)-float(each[4]) > 259200:
        voteclr = f"{BYEL}"
    else:
        voteclr = f"{BGRN}"

    ply = howmanyon(each[0])
    if gencfgver[0] != each[6]:
        vertxt = f'{BRED}({int(gencfgver[0])-int(each[6])} versions behind){RST}'
    else:
        vertxt = f'{GRN}(Current){RST}'

    if each[3] == "False":
        inrest = f"{GRN}False{RST}"
    else:
        inrest = f"{BYEL}TRUE{RST}"
    
    if ply != 0:
        mm = BGRN
    else:
        mm = BRED

    print(f'Server: {BMGT}{each[0].upper()}{RST} - Players: {mm}{ply}/50{RST}')
    print(f'Configuration version: {each[6]} {vertxt}')
    print(f'Server in restart: {inrest}')
    print(f'Last restart: {restclr}{restarted}{RST} - Reason: {each[5]}')
    print(f'Last wilddino wipe: {wipeclr}{lwipe}{RST}')
    print(f'Last wipe vote: {voteclr}{lvote}{RST}')
    print('  ')

print('        ')
conn.commit()
c.close()
conn.close()

