from colored import fg, bg, attr

RST = attr('reset')
RED = attr('reset') + fg(1)
YEL = attr('reset') + fg(3)
BYEL = attr('reset') + fg(11)
CYN = attr('reset') + fg(6)
BCYN = attr('reset') + fg(14)
BLU = attr('reset') + fg(32)
WHT = attr('reset') + fg(7)
BWHT = attr('reset') + fg(15)
MGT = attr('reset') + fg(5)
BMGT = attr('reset') + fg(13)
GRN = attr('reset') + fg(2)
BGRN = attr('reset') + fg(10)
PNK = attr('reset') + fg(9)
BRED = attr('reset') + fg(9)
PUR = attr('reset') + fg(99)
BRN = attr('reset') + fg(130)
BGN = attr('reset') + fg(86)
ORG = attr('reset') + fg(208)
SKN = attr('reset') + fg(222)
MAU = attr('reset') + fg(147)
RMY = attr('reset') + fg(100)
SLT = attr('reset') + fg(109)
DREV = attr('reverse')
LREV = bg(15) + attr('reverse')
UDL = attr('underlined')

# print(f'{RST}{RED}RED {RED}{LREV}RRED {BLU}BLUE {CYN}CYAN {BCYN}BCYAN {YEL}YELLOW {BYEL}BYELLOW {PNK}PINK \
#        {PUR}PURPLE {BRN}BROWN {GRN}GREEN {BGRN}BGREEN {BGN}BLUGREEN {ORG}ORANGE {SKN}SKIN {MAU}MAUVE \
#        {RMY}ARMY {SLT}SLATE{RST}')
