#!/usr/bin/env python3.7

import argparse
import sys
from os import nice

from loguru import logger as log

import modules.logging
from modules.discordbot import pyarkbot
from modules.processlock import PLock

parser = argparse.ArgumentParser()
parser.add_argument('-d', '--debug', action='store_true', help='verbose output (debug)')
parser.add_argument('-t', '--trace', action='store_true', help='verbose output (trace)')

args = parser.parse_args()

# Console Logging
if args.trace:
    log.add(sink=sys.stdout, level=5, backtrace=True, diagnose=True, colorize=True, format=modules.logging.longlogformat)
elif args.debug:
    log.add(sink=sys.stdout, level=10, backtrace=True, diagnose=True, colorize=True, format=modules.logging.longlogformat)

processlock = PLock()
processlock.lock()

nice(10)

pyarkbot()
