#!/usr/bin/python3

import discord
import asyncio
from cmdlistener import *

client = discord.Client()

@client.event
async def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')

@client.event
async def on_message(message):
    if message.content.startswith('!who') or message.content.startswith('!whoson'):
        #await asyncio.sleep(5)
        potime = 70
        conn = sqlite3.connect(sqldb)
        c = conn.cursor()
        c.execute('SELECT * FROM instances')
        srvrs = c.fetchall()
        for each in srvrs:
            c.execute('SELECT * FROM players WHERE server = ?', [each[0]])
            flast = c.fetchall()
            c.close()
            conn.close()
            pcnt = 0
            plist = ''
            for row in flast:
                chktme = time.time()-float(row[2])
                if chktme < potime:
                    print(row[1],chktme)
                    pcnt += 1
                    if plist == '':
                        plist = '%s' % (row[1])
                    else:
                        plist=plist + ', %s' % (row[1])
            if pcnt != 0:
                msg = f'{each[0]} has {pcnt} players online: {plist}'
                await client.send_message(message.channel, msg)
            else:
                msg = f'{each[0]} has no players online.'
                await client.send_message(message.channel, msg)

    elif message.content.startswith('!lastseen'):
        newname = message.content.split(' ')
        seenname = newname[1]
        conn = sqlite3.connect(sqldb)
        c = conn.cursor()
        c.execute('SELECT * FROM players WHERE playername = ?', [seenname])
        flast = c.fetchone()
        c.close()
        conn.close()
        if not flast:
            return 'no player found with that name'
        else:
            plasttime = elapsedTime(time.time(),float(flast[2]))
            if plasttime != 'now':
                msg = f'{seenname} was last seen {plasttime} ago on {flast[3]}'
                await client.send_message(message.channel, msg)
            else:
                msg = f'{seenname} is online now on {flast[3]}'
                await client.send_message(message.channel, msg)

client.run('NDkwNjQ2MTI2MDI3MDc5Njgw.DoNcWg.5LU6rycTgXNnApPL_6L2e9Tr5j0')
