#!/usr/bin/python3

from git import Repo

repo = Repo('/home/ark/pyark')


if repo.is_dirty():
    raise EnvironmentError('Current working directory is dirty.')

current_commit = repo.head.object.hexsha.encode('utf-8')
exp_commit = self.metadata['commit']
if current_commit != exp_commit:
    raise EnvironmentError("Commits don't match.\nCurrent: {}\nRecorded: {}".format(current_commit, exp_commit)) 

