#!/usr/bin/python3

import os
from git import Repo

localdir = '/home/ark/pyark'

repo = Repo(localdir)


origin = repo.remotes.origin
for each in dir(origin.repo):
    print(each)

print(repo.head.commit)
origin.fetch()
print(origin.repo.head.commit)
if repo.head.commit != origin.repo.head.commit:
    print('mismatched version. pulling')
    origin.pull()
print(repo.head.commit)
