#!/usr/bin/python3


import urllib.request, urllib.error, urllib.parse
import json

req = urllib.request.Request("https://linode.ghazlawl.com/ark/mods/auctionhouse/api/json/v1/auctions/?MarketID=GALAXY75")
opener = urllib.request.build_opener()
f = opener.open(req)
t =f.read()
print(t.decode()[:-20])
json = json.loads(t)

print (json)
#print json[0]['title']



