#!/usr/bin/python3

import time

def follow(stream):
    "Follow the live contents of a text file."
    line = ''
    for block in iter(lambda:stream.read(1024), None):
        if '\n' in block:
            # Only enter this block if we have at least one line to yield.
            # The +[''] part is to catch the corner case of when a block
            # ends in a newline, in which case it would repeat a line.
            for line in (line+block).splitlines(True)+['']:
                if line.endswith('\n'):
                    yield line
            # When exiting the for loop, 'line' has any remaninig text.
        elif not block:
            # Wait for data.
            time.sleep(1.0)
    # The End.

if __name__ == '__main__':
    # As a simple demonstration, run it with the filename to tail.
    import sys
    with open('/home/ark/saved/Logs/ShooterGame.log', 'rt') as following:
        following.seek(0, 2)
        try:
            for line in follow(following):
                sys.stdout.write(line)
        except KeyboardInterrupt:
            pass

