#!/usr/bin/python3

from subprocess import check_call as run 
from getopt import getopt, GetoptError 
RELEASE = 'master' # default release 
SRC_DIR = "/home/ark/pyark" # checkout directory 
UPDATE_CMD = ( # base command 
'git@github.com:cosmicc/pyark.git' 
)

def update(): 
    sudo = False 
    src_dir = SRC_DIR 
    release = RELEASE 
    commit = None 

    if release[0].isdigit(): ## Check if it is a version 
        release = 'r' + release 
    release = 'origin/' + release ## assume it is a branch

    if commit is not None: ## if a commit is supplied use that 
        cmd = UPDATE_CMD % (src_dir, commit) 
    else: 
        cmd = UPDATE_CMD % (src_dir, release)

    if sudo: 
        run('sudo %s' % cmd) 
    else: 
        run(cmd)

update()
