#!/usr/bin/env python3.7

import argparse
import subprocess
import sys
import time
from os import system
from sys import exit

import redis

from modules.colorizer import (BCYN, BGN, BGRN, BLU, BMGT, BRED, BWHT, BYEL, GRN, LREV,
                               MAU, MGT, ORG, PUR, RED, RMY, RST, SKN, SLT, WHT, YEL)
from modules.configreader import redis_host, redis_port

r = redis.Redis(host=redis_host, port=redis_port, db=0)
allservers = r.smembers('servers')


def _loglevel(args):
    args.subparser_name = f'{args.subparser_name}:{args.loglevel}'
    _execute(args)


def _log(args):
    if args.debug:
        command = f'/home/ark/pyark/logclient {args.lines} -d'
    else:
        command = f'/home/ark/pyark/logclient {args.loglines}'
    subprocess.run(command, stdout=sys.stdout, stderr=sys.stderr, shell=True)


def _execute(args):
    print(f'args: {args.subparser_name}')
    print(f'server: {args.servername}')
    if args.servername.encode() in allservers:
        print(f'Running pyark start on server: [{args.server}]\n')
        r.publish(f'{args.servername.lower()}-commands', f'{args.subparser_name}')
    elif args.servername.lower() == 'all':
        print(f'Running pyark {args.subparser_name} on {len(allservers)} servers: [{allservers}]\n')
        for server in allservers:
            r.publish(f'{server.decode()}-commands', f'{args.subparser_name}')
    else:
        print(f'You need to specify a valid server to execute {args.subparser_name} on\n')


parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(title='action', description='valid actions to perform', dest='subparser_name')

parser_start = subparsers.add_parser('start')
parser_start.add_argument('servername')
parser_start.set_defaults(func=_execute)

parser_stop = subparsers.add_parser('stop')
parser_stop.add_argument('servername')
parser_stop.set_defaults(func=_execute)

parser_restart = subparsers.add_parser('restart')
parser_restart.add_argument('servername')
parser_restart.set_defaults(func=_execute)

parser_update = subparsers.add_parser('update')
parser_update.add_argument('servername')
parser_update.set_defaults(func=_execute)

parser_kill = subparsers.add_parser('kill')
parser_kill.add_argument('servername')
parser_kill.set_defaults(func=_execute)

parser_gitpull = subparsers.add_parser('gitpull')
parser_gitpull.add_argument('servername')
parser_gitpull.set_defaults(func=_execute)

parser_rw = subparsers.add_parser('restartwatchdog')
parser_rw.add_argument('servername')
parser_rw.set_defaults(func=_execute)

parser_log = subparsers.add_parser('log')
parser_log.add_argument('-l', '--lines', default=20, help='Previous log lines to show')
parser_log.add_argument('-d', '--debug', help='Include debug logs')
parser_log.set_defaults(func=_log)

parser_log = subparsers.add_parser('loglevel')
parser_log.add_argument('level', help='Loglevel to set to')
parser_log.set_defaults(func=_loglevel)


args = parser.parse_args()
args.func(args)

print('    ')

null = None


def oldkillall():
    with open('/tmp/pyark.pid') as inf:
        for line in inf:
            system(f'kill -9 {line}')
    print('All pyark processes killed.')


def percentage(part, whole):
    return 100 * float(part) / float(whole)


def getresponse(question):
    print('    ')
    check = str(input(f"{question} : ")).lower().strip()
    try:
        return check
    except Exception as error:
        print("Please enter valid inputs")
        print(error)
        exit()


def ask_question(question):
    print('   ')
    check = str(input(f"{question} (Y/N): ")).lower().strip()
    try:
        if check[0] == 'y':
            return True
        elif check[0] == 'n':
            return False
        else:
            print('Invalid Input')
            exit()
    except Exception as error:
        print("Please enter valid inputs")
        print(error)
        exit()


def banplayer():
    printcolmns('players')
    showtable('players')
    nsteamid = getresponce(f'{BGRN}Enter Steam ID of player to BAN{RST}')
    oplayers = db_getall("players")
    juu = 'noname'
    for each in oplayers:
        if each[0] == nsteamid:
            juu = each[1]
    if ask_question(f'{BGRN}You will be BANNING {BMGT}{juu}{BGRN} with steamid {BMGT}{nsteamid}{BGRN} from the \
cluster. continue?{RST}'):
        if juu != 'noname':
            dbupdate("UPDATE players SET banned = '%s' WHERE steamid = '%s'" % (time.time(), nsteamid))
        blid = dbquery("SELECT * from banlist WHERE steamid = '%s'" % (nsteamid, ))
        if not blid:
            dbupdate("INSERT INTO banlist (steamid) VALUES ('%s')" % (nsteamid, ))
        print('    ')
        print(f'{BYEL}Player {BMGT}{each[1]}{BYEL} with steamid {BMGT}{each[0]}{BYEL} has been BANNED from all servers \
in the cluster!{RST}')
        print('    ')
    else:
        print('    ')
        print(f'{BRED}Canceled. Skipping ban{RST}')
        print('    ')
    alldata = db_getall("banlist")
    for row in alldata:
        print(row)


def unbanplayer():
    printcolmns('players')
    showtable('players')
    nsteamid = getresponce(f'{BGRN}Enter Steam ID of player to UN-BAN{RST}')
    oplayers = db_getall("players")
    juu = 'noname'
    for each in oplayers:
        if each[0] == nsteamid:
            juu = each[1]
    if ask_question(f'{BGRN}You will be UN-BANNING {BMGT}{juu}{BGRN} with steamid {BMGT}{nsteamid}{BGRN} \
from the cluster. continue?{RST}'):
        if juu != 'noname':
            dbupdate("UPDATE players SET banned = '' WHERE steamid = '%s'" % (nsteamid,))
        blid = dbquery("SELECT * from banlist WHERE steamid = '%s'" % (nsteamid,))
        if blid:
            dbupdate("DELETE FROM banlist WHERE steamid = '%s'" % (nsteamid,))
        print('    ')
        print(f'{BYEL}Player {BMGT}{each[1]}{BYEL} with steamid {BMGT}{each[0]}{BYEL} has been UN-BANNED from \
all servers in the cluster!{RST}')
        print('    ')
    else:
        print('    ')
        print(f'{BRED}Canceled. Skipping un-ban{RST}')
        print('    ')
    alldata = db_getall("banlist")
    for row in alldata:
        print(row)


def banlist():
    oplayers = dbquery("SELECT * from players WHERE banned != ''")
    for each in oplayers:
        print(f'{BCYN}{each}{RST}')
    if not oplayers:
        print(f'{BGRN}No player list bans{RST}')
    print('    ')
    oplayers = db_getall("banlist")
    for each in oplayers:
        print(f'{BYEL}{each}{RST}')
    if not oplayers:
        print(f'{BGRN}No ids in ban list{RST}')
    print('    ')


def tribewipe():
    tribeid = getresponse(f'{BGRN}Enter Tribe ID of tribe to DESTROY{RST}')
    if ask_question(f'{BGRN}You will be DESTROYING {BMGT}{tribeid}{BGRN} from the cluster. continue?{RST}'):
        subrun = f"""arkmanager rconcmd 'DestroyTribeIdStructures {tribeid}' @ragnarok"""
        subprocess.run(subrun, shell=True)
        # subrun = f"""arkmanager rconcmd 'DestroyTribeIdDinos {tribeid}' @all && arkmanager rconcmd \
        # 'DestroyTribeIdStructures {tribeid}' @all && arkmanager rconcmd 'DestroyTribeIdPlayers \
        # {tribeid}' @all && arkmanager rconcmd 'DestroyTribeId {tribeid}' @all"""
        print('    ')
        print(f'{BYEL}Removing tribeid {BMGT}{tribeid}{BYEL} from local server{RST}')
        print('   ')
        # subprocess.run('arkmanager rconcmd "saveworld" @all && arkmanager backup @all', shell=True)
        subprocess.run(subrun, shell=True)
        print(f'{BYEL}Removing tribeid {BMGT}{tribeid}{BYEL} from remote server{RST}')
        # sendtoserver(tribeid)
        # print('   ')
        # print(f'{BGRN}TribeID {BMGT}{tribeid}{BGRN} has been DESTROYED from all servers!{RST}')
