#!/bin/bash

nowtime=`date '+%Y-%m-%d-%H-%M'`;
pg_dumpall -c | gzip > /home/ark/shared/db/full_$nowtime.gz
pg_dump -s -c -C --serializable-deferrable pyark | gzip > /home/ark/shared/db/pyark_schema_$nowtime.gz
pg_dump --insert -a --serializable-deferrable pyark | gzip > /home/ark/shared/db/pyark_data_$nowtime.gz
pg_dump -s -c -C --serializable-deferrable pyarkstats | gzip > /home/ark/shared/db/pyarkstats_schema_$nowtime.gz
pg_dump --insert -a --serializable-deferrable pyarkstats | gzip > /home/ark/shared/db/pyarkstats_data_$nowtime.gz
find /home/ark/shared/db/* -type f -ctime +30 | xargs rm -rf
