#!/bin/bash

nowtime=`date '+%Y-%m-%d-%H-%M'`;

rsync -arq /home/ark/shared/ark-backups /mnt/backup/ark_backup/
rsync -arq /home/ark/shared/config /mnt/backup/ark_backup/
rsync -arq /home/ark/shared/db /mnt/backup/ark_backup/
rsync -arq /home/ark/shared/logs /mnt/backup/ark_backup/
rsync -arq /home/ark/shared/cluster-backups /mnt/backup/ark_backup/
find /home/ark/shared/ark-backups/* -type d -ctime +30 | xargs rm -rf
find /home/ark/shared/db/* -type d -ctime +30 | xargs rm -rf
find /home/ark/shared/logs/* -type d -ctime +30 | xargs rm -rf
