#!/usr/bin/python3

import threading
import subprocess
import argparse, sqlite3
from configparser import ConfigParser
from datetime import datetime
from datetime import time as dt
import time

configfile = '/home/ark/pyark.cfg'

class ExtConfigParser(ConfigParser):
    def getlist(self, section, option):
        value = self.get(section, option)
        return list(filter(None, (x.strip() for x in value.split(','))))

    def getlistint(self, section, option):
        return [int(x) for x in self.getlist(section, option)]

config = ExtConfigParser()
config.read(configfile)

sharedpath = config.get('general', 'shared')

now = time.time()

sqldb = f'{sharedpath}/db/pyark.db'


conn = sqlite3.connect(sqldb)
c = conn.cursor()

##delete the admin account from db
#c.execute('DELETE from players WHERE steamid = 76561198408657294')

#c.execute('SELECT * from players WHERE discordid = None')
#c.execute('UPDATE players SET discordid = "" WHERE playername = "eclipse"')
#c.execute('CREATE TABLE IF NOT EXISTS chatbuffer (server TEXT, name TEXT, message TEXT)')
c.execute('ALTER TABLE chatbuffer ADD COLUMN timestamp TEXT')
#c.execute('DROP TABLE discornames')
#c.execute('INSERT INTO general ("cfgver") VALUES ("1")')
#c.execute('PRAGMA table_info(players)')
#c.execute('UPDATE players SET firstseen = ? WHERE steamid = ?', (now,'76561198028548947'))
conn.commit()



alldata = c.fetchall()
ap = []
for row in alldata:
    print(row)

c.close()
conn.close()

