#!/usr/bin/python3

import sqlite3, time
from numpy.random import seed, shuffle, randint
from numpy import argmax
from configreader import *

linfo = [18, 'points', '50', '1538860583.11985', 50, 2, 6, 'Incomplete', 1]
winners = []
picks = []
adjpicks = []
wins = []
conn4 = sqlite3.connect(sqldb)
c4 = conn4.cursor()
c4.execute('SELECT * FROM lotteryplayers')
lottoers = c4.fetchall()
#c4.execute('SELECT * FROM lotteryinfo WHERE id = ?', (linfo[0],))
#linfo = c4.fetchone()
c4.close()
conn4.close()
if len(lottoers) >= 4:
    for eachn in lottoers:
        winners.append(eachn[0])
    seed(randint(100))
    shuffle(winners)
    seed (randint(100))
    for eachw in range(len(winners)):
        picks.append(randint(100))
        conn4 = sqlite3.connect(sqldb)
        c4 = conn4.cursor()
        c4.execute('SELECT lottowins FROM players WHERE steamid = ?', (winners[eachw],))
        lwins = c4.fetchone()
        c4.close()
        conn4.close()
        wins.append(lwins[0])
        if wins[eachw] > 10:
            adjj = 10
        else:
            adjj = wins[eachw]
        adjpicks.append(picks[eachw]-adjj*5)
    winneridx = argmax(adjpicks)
    winnersid = winners[winneridx]


print(winners)
print(picks)
print(wins)
print(adjpicks)
print(winners[winneridx])

