#!/usr/bin/python3

import subprocess 

def getinstpid(inst):
    rawpid = subprocess.run('arkmanager getpid @%s' % (inst), stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, shell=True)
    return rawpid.stdout.decode('utf-8').split('\n')[1]


def getinstmem(inst):
    inst = getinstpid(inst)
    rawsts = subprocess.run('ps -p %s -o rss,vsz' % (inst), stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, shell=True)
    instrss, instvsz = rawsts.stdout.decode('utf-8').split('\n')[1].split(' ')
    instrss = int(instrss)/1000000 // 0.01 / 100
    instvsz = int(instvsz)/1000000 // 0.01 / 100
    return instrss,instvsz

print(getinstmem('island'))
