#!/usr/bin/python3

import json 
from urllib.request import urlopen
import urllib.request
import io
u = urllib.request.urlopen("https://ark-servers.net/api/?object=servers&element=detail&key=6TO5zDDQk9uiywI9aJp9IYjmZmNHZn98DzE", data = None)
f = io.TextIOWrapper(u,encoding='utf-8')
print(f.read())

def fetcharkserverdata():
    #data = urlopen('https://ark-servers.net/api/?object=servers&element=detail&key=6TO5zDDQk9uiywI9aJp9IYjmZmNHZn98DzE').read()
    #print(data)
    data = urlopen('https://ark-servers.net/api/?object=servers&element=detail&key=6TO5zDDQk9uiywI9aJp9IYjmZmNHZn98DzE')
    print(data.read())
    adata = json.loads(data)
    print(adata)
    for each in adata:
        print(each)

