#!/usr/bin/env python3.7

import argparse
from os import nice

import modules.logging
from modules.configreader import webserver_ip, webserver_port
from modules.processlock import PLock
from web import create_app, socketio

__name__ = 'webserver'

parser = argparse.ArgumentParser()
parser.add_argument('-d', '--debug', action='store_true', help='verbose output (debug)')

args = parser.parse_args()

processlock = PLock()
processlock.lock()

nice(12)

if args.debug:
    app = create_app('config.DevelopmentConfig')
    socketio.run(app, host=webserver_ip, port=51501)
else:
    app = create_app('config.BaseConfig')
    socketio.run(app, host=webserver_ip, port=webserver_port)
